// <auto-generated />
namespace BackEndGSBrevet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_roleId_to_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_roleId_to_users));
        
        string IMigrationMetadata.Id
        {
            get { return "202003291210208_add_roleId_to_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
